Footer story
ApolloXI14/exodus pull request #48
Opened 2021-12-21 01:19 UTC by CintBX

2021-12-25 21:13 UTC, CintBX commented on pages/story/[id].js
> +	};
Forgot to mention @ApolloXI14 that the background image for story pages were not darkened like they are in the wordpress site (for better text readability)
This change is unrelated to the Footer but I figure it small enough to do it here.

2021-12-25 21:14 UTC, CintBX commented on pages/story/index.js
>    }
Forgot to mention @ApolloXI14 that the background image for story pages were not darkened like they are in the wordpress site (for better text readability)
This change is unrelated to the Footer but I figure it small enough to do it here.

2021-12-29 01:49 UTC, ApolloXI14 requested changes

2021-12-29 01:49 UTC, ApolloXI14 commented on pages/exodus/[subpage].js
> +      }
Instead of a ternary that returns _null_ if false, why not just use a conditional?

E.g.

`{  showScrollArrow && (<ScrollToTop />) }`

2021-12-29 01:49 UTC, ApolloXI14 commented on pages/exodus/index.js
> +      <Footer />
Instead of a ternary that returns null if false, why not just use a conditional?

E.g.

`{ showScrollArrow && (<ScrollToTop />) }`

2022-01-01 02:41 UTC, CintBX commented on pages/exodus/[subpage].js
> +      }
done!

2022-01-01 02:41 UTC, CintBX commented on pages/exodus/index.js
> +      <Footer />
done!

2022-01-12 22:36 UTC, ApolloXI14 approved these changes

2022-01-12 22:37 UTC, merged